F_SALES_CHANNEL = "sales_channel"
F_DISTRIBUTION_CHANNEL = "distribution_channel"
F_BRAND = "brand"
F_YEAR_WEEK = "year_week"
F_SALES = "sales"

V_ON_TRADE = "on_trade"
V_OFF_TRADE = "off_trade"
V_RETAILERS = "RE"
V_SUPERMARKETS = "SM"
V_RESTAURANTS = "RS"
V_BARS = "BA"
V_ABSOLUT = "absolut"
V_JAMESON = "jameson"